# Generated by Django 4.2.5 on 2023-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dept',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
