# Generated by Django 4.2.5 on 2023-09-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_alter_customer_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
