# Generated by Django 4.2.5 on 2023-09-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0005_order_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='last_update',
        ),
        migrations.AddField(
            model_name='order',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
