# Generated by Django 4.2.5 on 2023-09-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0007_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned_dept',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
