# Generated by Django 4.2.2 on 2023-09-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0008_order_returned_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyTurnDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('whichDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.order')),
            ],
        ),
    ]
