# Generated by Django 4.2.5 on 2023-09-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0009_historyturndept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finished',
        ),
        migrations.AddField(
            model_name='order',
            name='dept',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
