# Generated by Django 4.2.5 on 2023-09-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0010_remove_order_finished_order_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deptor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='returned_dept',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
