# Generated by Django 4.2.5 on 2023-09-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0012_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dateReturn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
