# Generated by Django 4.2.5 on 2023-09-22 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0013_customer_datereturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyturndept',
            name='whichDept',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='order',
            name='returned_dept',
        ),
        migrations.AddField(
            model_name='historyturndept',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a1.customer'),
            preserve_default=False,
        ),
    ]
